name = "chai-data"
main = "src/worker.ts"
compatibility_date = "2023-08-14"

[[kv_namespaces]]
binding = "REFERENCE"
id = "c4aea1d089f64920b95ee9be79e3f8f6"

[[d1_databases]]
binding = "CHAI"
database_name = "chai"
database_id = "241850ca-f3d4-465a-b365-2dc489841ea1"
